stages:
  - eslint
  - test

elsint:
  stage: eslint
  image: node:latest
  allow_failure: true
  script:
    - npm install
    - ./node_modules/.bin/eslint lib/classes

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - node ./node_modules/mocha/bin/_mocha --require test/utils.js test/**/*.test.js

coverage:
  stage: test
  image: node:latest
  script:
    - npm install
    - NODE_ENV=test node_modules/.bin/nyc --reporter=lcovonly mocha --require test/utils.js test/**/*.test.js
    - node_modules/.bin/codecov -t ${CODECOV_TOKEN}
